//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColaComNois.Context.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccn_despesas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ccn_despesas()
        {
            this.ccn_rateios = new HashSet<ccn_rateios>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public float Valor { get; set; }
        public System.DateTime Data_Vencimento { get; set; }
        public Nullable<System.DateTime> Data_Pagamento { get; set; }
        public string Status { get; set; }
        public string Observacao { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ccn_rateios> ccn_rateios { get; set; }
    }
}
