//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColaComNois.Context.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ccn_rateios
    {
        public int Id { get; set; }
        public int IdJogador { get; set; }
        public int IdRecebedor { get; set; }
        public int IdDespesa { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime Data_Pagamento { get; set; }
    
        public virtual ccn_despesas ccn_despesas { get; set; }
        public virtual ccn_jogadores ccn_jogadores { get; set; }
        public virtual ccn_jogadores ccn_jogadores1 { get; set; }
    }
}
