//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColaComNois.Context.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ccn_adversarios> ccn_adversarios { get; set; }
        public virtual DbSet<ccn_despesas> ccn_despesas { get; set; }
        public virtual DbSet<ccn_jogadores> ccn_jogadores { get; set; }
        public virtual DbSet<ccn_jogos> ccn_jogos { get; set; }
        public virtual DbSet<ccn_logins> ccn_logins { get; set; }
        public virtual DbSet<ccn_rateios> ccn_rateios { get; set; }
    }
}
